### ISSUE TITLE
Some warm resets fail

### ISSUE THREAD

**Issue by bluewww** [pulp-platform/carfield#92]
I don't know the cause yet but the reset sequence fails somewhere during isolation

* [x] Fix PULP warm reset
~~* [ ] Fix Periph warm  reset~~ -> can be done, but no use case for peripheral domain reset
* [x] Fix Security island warm reset
* [x] Fix L2 warm reset

**Comment by yvantor** [comment]
Thanks for reporting, I will have a look in the cluster.
